FROM library/postgres
ENV POSTGRES_USER summaries_sk_wikipedia
ENV POSTGRES_PASSWORD summaries_sk_wikipedia
ENV POSTGRES_DB summaries_sk_wikipedia
ADD docker-entrypoint-initdb.d /docker-entrypoint-initdb.d/